# Generated by Django 3.2.7 on 2021-09-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoapp', '0003_alter_status_timeleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='uploadState',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
