# Generated by Django 3.2.7 on 2022-01-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoapp', '0004_alter_status_uploadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='inactive',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
